apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: retail-app

resources:
  - namespace.yaml
  - ui-deployment.yaml
  - ui-service.yaml
  - catalog-deployment.yaml
  - catalog-service.yaml
  - orders-deployment.yaml
  - orders-service.yaml
  - carts-deployment.yaml
  - carts-service.yaml
  - checkout-deployment.yaml
  - checkout-service.yaml
  - assets-deployment.yaml
  - assets-service.yaml
  - ingress.yaml

commonLabels:
  app.kubernetes.io/created-by: retail-store-sample
