apiVersion: apps/v1
kind: Deployment
metadata:
  name: ui
  labels:
    app.kubernetes.io/component: service
    app.kubernetes.io/name: ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: service
      app.kubernetes.io/name: ui
  template:
    metadata:
      labels:
        app.kubernetes.io/component: service
        app.kubernetes.io/name: ui
    spec:
      containers:
      - name: ui
        image: public.ecr.aws/aws-containers/retail-store-sample-ui:0.7.0
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
          protocol: TCP
        env:
        - name: ENDPOINTS_CATALOG
          value: http://catalog:8080
        - name: ENDPOINTS_CARTS
          value: http://carts:8080
        - name: ENDPOINTS_CHECKOUT
          value: http://checkout:8080
        - name: ENDPOINTS_ORDERS
          value: http://orders:8080
        - name: ENDPOINTS_ASSETS
          value: http://assets:8080
        resources:
          limits:
            memory: 512Mi
          requests:
            cpu: 250m
            memory: 512Mi
